FROM javert899/pm4py:latest

RUN pip install jupyter jupyterlab matplotlib seaborn py2neo && \
	jupyter notebook --generate-config && \
	echo "c.NotebookApp.ip = '0.0.0.0'" >> /root/.jupyter/jupyter_notebook_config.py && \
	echo "c.NotebookApp.port = 8080" >> /root/.jupyter/jupyter_notebook_config.py && \
	echo "c.NotebookApp.allow_root = True" >> /root/.jupyter/jupyter_notebook_config.py && \
	apt-get -y autoremove && \
	apt-get -y clean && \
	rm -r /root/.cache/pip

ENTRYPOINT jupyter notebook
